# Generated by Django 5.1.2 on 2024-10-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('botanical_name', models.TextField(default=' ', max_length=100)),
                ('weather', models.TextField(default=' ', max_length=500)),
                ('How_to_Handle_Tips', models.TextField(default=' ', max_length=500)),
                ('proadd', models.TextField(default='')),
                ('category', models.CharField(choices=[('H', 'Herb'), ('S', 'Shrub'), ('T', 'trees'), ('Cmb', 'Climber'), ('Cpr', 'Creeper'), ('FP', 'Flowering Plants'), ('Plants', 'Plants'), ('GT', 'Gardening Tool'), ('AG', 'Agro Chemicals')], max_length=50)),
                ('product_image', models.ImageField(upload_to='product/')),
            ],
        ),
    ]
