# Generated by Django 5.1.2 on 2024-10-10 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('Used_for', models.TextField(default=' ', max_length=500)),
                ('tool_image', models.ImageField(upload_to='tool/')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('H', 'Herb'), ('S', 'Shrub'), ('T', 'trees'), ('Cmb', 'Climber'), ('Cpr', 'Creeper'), ('FP', 'Flowering Plants')], max_length=50),
        ),
    ]
