# Generated by Django 5.1.2 on 2024-10-10 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tool_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=20)),
                ('selling_price', models.FloatField()),
                ('description', models.CharField(default='', max_length=200)),
                ('Uses', models.TextField(default=' ', max_length=500)),
                ('agro_image', models.ImageField(upload_to='agro/')),
            ],
        ),
    ]
