# Generated by Django 5.1.2 on 2024-10-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_agro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('H', 'Herb'), ('S', 'Shrub'), ('T', 'trees'), ('Cmb', 'Climber'), ('Cpr', 'Creeper'), ('FP', 'Flowering Plants')], max_length=50)),
            ],
        ),
    ]
