# Generated by Django 5.1.2 on 2024-10-10 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('soil_type', models.CharField(max_length=50)),
                ('sowing_month', models.CharField(max_length=50)),
                ('seed_image', models.ImageField(upload_to='seed/')),
            ],
        ),
        migrations.CreateModel(
            name='Soil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('useful_for', models.CharField(max_length=100)),
                ('crops_to_sow', models.CharField(max_length=150)),
                ('soil_image', models.ImageField(upload_to='soil/')),
            ],
        ),
    ]
