# Generated by Django 5.1.2 on 2024-10-11 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
