# Generated by Django 5.1.2 on 2024-10-11 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_customer_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='password',
        ),
    ]
