# Generated by Django 5.1.2 on 2024-10-11 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_customer_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
