# Generated by Django 5.1.2 on 2024-10-11 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_customer_user_customer_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
