# Generated by Django 5.1.2 on 2024-10-12 06:17

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_customer_mobile_alter_customer_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='preference',
            field=models.CharField(default='', max_length=50, verbose_name=app.models.Category),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(choices=[('H', 'Herb'), ('S', 'Shrub'), ('T', 'trees'), ('Cmb', 'Climber'), ('Cpr', 'Creeper'), ('FP', 'Flowering Plants')], default='', max_length=50),
        ),
    ]
