# Generated by Django 5.1.2 on 2024-10-12 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_customer_preference_alter_category_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='preference',
        ),
        migrations.AddField(
            model_name='customer',
            name='preference',
            field=models.ManyToManyField(default='', max_length=50, to='app.category'),
        ),
    ]
