# Generated by Django 5.1.2 on 2024-10-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_remove_customer_preference_customer_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(choices=[('H', 'Herb'), ('S', 'Shrub'), ('T', 'trees'), ('Cmb', 'Climber'), ('Cpr', 'Creeper'), ('FP', 'Flowering Plants')], max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='preference',
            field=models.ManyToManyField(default=None, max_length=50, to='app.category'),
        ),
    ]
