# Generated by Django 5.1.2 on 2024-10-12 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_customer_pincode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='preference',
        ),
    ]
