# Generated by Django 5.1.2 on 2024-10-14 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='agro',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='tool',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
