# Generated by Django 5.1.2 on 2024-10-14 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_remove_cartitem_agro_remove_cartitem_product_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('agro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.agro')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('seed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.seed')),
                ('soil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.soil')),
                ('tool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
