# Generated by Django 5.1.2 on 2024-10-15 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_remove_cart_agros_remove_cart_products_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
