# Generated by Django 5.1.2 on 2024-10-16 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='agro',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='seed',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='soil',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='tool',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
