# Generated by Django 5.1.2 on 2024-10-19 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_payment_orderplaced'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.DeleteModel(
            name='OrderPlaced',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
