# Generated by Django 5.1.2 on 2024-10-20 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_remove_cart_created_at_cart_timestamp_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInteraction',
        ),
    ]
