# Generated by Django 5.1.2 on 2024-10-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_delete_userinteraction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchhistory',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
