# Generated by Django 5.1.2 on 2024-10-20 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_alter_searchhistory_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchhistory',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='visithistory',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
