# Generated by Django 5.1.2 on 2024-10-20 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_alter_searchhistory_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.product'),
        ),
    ]
