# Generated by Django 5.1.2 on 2024-10-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_searchhistory_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Agro',
        ),
        migrations.DeleteModel(
            name='Seed',
        ),
        migrations.DeleteModel(
            name='Soil',
        ),
        migrations.DeleteModel(
            name='Tool',
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(choices=[('H', 'Herb'), ('S', 'Shrub'), ('T', 'trees'), ('Cmb', 'Climber'), ('Cpr', 'Creeper'), ('FP', 'Flowering Plants'), ('AG', 'Agro'), ('Seed', 'Seed'), ('Soil', 'Soil'), ('Tool', 'Tool')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='botanical_name',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('H', 'Herb'), ('S', 'Shrub'), ('T', 'trees'), ('Cmb', 'Climber'), ('Cpr', 'Creeper'), ('FP', 'Flowering Plants'), ('AG', 'Agro'), ('Seed', 'Seed'), ('Soil', 'Soil'), ('Tool', 'Tool')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='discounted_price',
            field=models.FloatField(blank=True),
        ),
    ]
