# Generated by Django 5.1.2 on 2024-11-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_alter_customer_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.IntegerField(max_length=10),
        ),
    ]
